(use graviton)

(define (main args)
  (let1 img (create-image 640 480)
    (set-coordinate! img -6 4 6 -4)
    (draw-line img '((-6 0) (6 0)) (color 'aqua))
    (draw-line img '((0 6) (0 -6)) (color 'aqua))
    (draw-line img (map (^x (list x (* 2 (sin x)))) (iota 121 -6 0.1)) (color 'white))
    (display-image img))
  0)