(use file.util)
(use gauche.sequence)
(use graviton)
(use srfi-42)

(define *script-dir* (sys-dirname (current-load-path)))

(define (main args)
  (grv-begin
    (let* ((win (make-window *program-name* 640 480 :fullscreen? #t))
           (img (load-image (build-path *script-dir* "font_8x16.png")))
           (tiles (divide-image img 8 16))
           (tilemap (make-tile-map win tiles 80 30 320 240))
           (out (tile-map->output-port tilemap)))
      (display "System colors:\n" out)
      (do-ec (: color 0 8)
             (format out "\x1b[48;5;~am  " color))
      (display "\x1b[0m\n" out)
      (do-ec (: color 8 16)
             (format out "\x1b[48;5;~am  " color))
      (display "\x1b[0m\n\n" out)
      (display "Color cube, 6x6x6:\n" out)
      (dotimes (green 6)
        (dotimes (red 6)
          (dotimes (blue 6)
            (format out "\x1b[48;5;~am  " (+ 16 (* red 36) (* green 6) blue)))
          (display "\x1b[0m " out))
        (newline out))

      (display "Grayscale ramp:\n" out)
      (do-ec (: color 232 256)
             (format out "\x1b[48;5;~am  " color))
      (display "\x1b[0m\n\n" out)

      (on-key-up win (scan key mod repeat?)
        (case scan
          ((escape)
           (destroy-window win))))
      )
    )
  0)
