(use gauche.parseopt)
(use graviton)
(use graviton.grut)

(define (main args)
  (let-args (cdr args)
      ((force-player? "player" #f)
       (force-browser? "browser" #f))
    (grv-config :client (cond
                          (force-player? 'player)
                          (force-browser? 'browser)
                          (else #f)))
    (with-window (grut-canvas-window 400 200)
        (canvas)
      (let1 ctx (canvas'get-context "2d")
        (on-jsevent window "keyup" (key)
          (when (equal? key "Escape")
            (close-window)))

        (ctx'begin-path)
        (ctx'move-to 20 20)
        (ctx'line-to 200 20)
        (ctx'line-to 120 120)
        (ctx'close-path)
        (ctx'stroke)
        (ctx'clear-rect 10 10 100 100)))))
