(use graviton)
(use graviton.canvas)

(define (main args)
  (grv-begin
    (set-window-event-handler! 'keyup (lambda (event)
                                        (when (equal? (slot-ref event 'code) "Escape")
                                          (app-close))))
    (make-canvas 300 150)
    (begin-path)
    (move-to 20 140)
    (line-to 120 10)
    (line-to 220 140)
    (close-path)
    (stroke))
  0)
