(use graviton)
(use graviton.grut)

(define (main args)
  (with-window (grut-canvas-window 300 150)
      (canvas)
    (let1 ctx (canvas'get-context "2d")
      (on-jsevent window "keyup" (key)
        (when (equal? key "Escape")
          (close-window)))

      (ctx'begin-path)
      (ctx'move-to 20 140)
      (ctx'line-to 120 10)
      (ctx'line-to 220 140)
      (ctx'close-path)
      (ctx'stroke))))
