(use graviton)
(use graviton.canvas)

(define (main args)
  (grv-begin
    (set-window-event-handler! 'keyup (lambda (event)
                                        (when (equal? (slot-ref event 'code) "Escape")
                                          (app-close))))
    (make-canvas 300 150)
    (begin-path)
    (move-to 30 90)
    (line-to 110 20)
    (line-to 240 130)
    (line-to 60 130)
    (line-to 190 20)
    (line-to 270 90)
    (close-path)
    (set-fill-style! "green")
    (fill 'evenodd))
  0)
