(use graviton)
(use graviton.grut)

(define (main args)
  (with-window (grut-canvas-window 300 150)
      (canvas)
    (let1 ctx (canvas'get-context "2d")
      (on-jsevent window "keyup" (key)
        (when (equal? key "Escape")
          (close-window)))

      (ctx'begin-path)
      (ctx'move-to 30 90)
      (ctx'line-to 110 20)
      (ctx'line-to 240 130)
      (ctx'line-to 60 130)
      (ctx'line-to 190 20)
      (ctx'line-to 270 90)
      (ctx'close-path)
      (set! (~ ctx'fill-style) "green")
      (ctx'fill "evenodd"))))
