(use gauche.logger)
(use gauche.parseopt)
(use graviton)
(use graviton.grut)

(define (main args)
  (let-args (cdr args)
      ((force-player? "player" #f)
       (force-browser? "browser" #f))
    (grv-config :client (cond
                          (force-player? 'player)
                          (force-browser? 'browser)
                          (else #f)))
    (with-window (grut-canvas-window 300 150)
        (canvas)
      (let1 ctx (canvas'get-context "2d")
        (on-jsevent window "keyup" (key)
          (when (equal? key "Escape")
            (close-window)))

        (ctx'rect 10 10 100 100)
        (ctx'fill)

        (on-jsevent canvas "click" (offset-x offset-y)
          (log-format "(~a, ~a) in path?: ~a" offset-x offset-y (ctx'is-point-in-path offset-x offset-y)))))))
