(use graviton)
(use graviton.canvas)

(define (main args)
  (grv-begin
    (set-window-event-handler! 'keyup (lambda (event)
                                        (when (equal? (slot-ref event 'code) "Escape")
                                          (app-close))))
    (make-canvas 300 150)
    (move-to 90 130)
    (line-to 95 25)
    (line-to 150 80)
    (line-to 205 25)
    (line-to 210 130)
    (set-line-width! 15)
    (stroke))
  0)
