;;;; Generated automatically from SDL header files.
(inline-stub
 (define-cfn
  state->symbol
  (v :: Uint8)
  ::ScmObj
  :static
  (case v ((SDL_RELEASED) (return (quote released)))
   ((SDL_PRESSED) (return (quote pressed))) (else (return (quote unknown)))))
 (define-cfn
  scancode->symbol
  (v :: SDL_Scancode)
  ::ScmObj
  :static
  (case v ((SDL_SCANCODE_A) (return (quote a)))
   ((SDL_SCANCODE_B) (return (quote b))) ((SDL_SCANCODE_C) (return (quote c)))
   ((SDL_SCANCODE_D) (return (quote d))) ((SDL_SCANCODE_E) (return (quote e)))
   ((SDL_SCANCODE_F) (return (quote f))) ((SDL_SCANCODE_G) (return (quote g)))
   ((SDL_SCANCODE_H) (return (quote h))) ((SDL_SCANCODE_I) (return (quote i)))
   ((SDL_SCANCODE_J) (return (quote j))) ((SDL_SCANCODE_K) (return (quote k)))
   ((SDL_SCANCODE_L) (return (quote l))) ((SDL_SCANCODE_M) (return (quote m)))
   ((SDL_SCANCODE_N) (return (quote n))) ((SDL_SCANCODE_O) (return (quote o)))
   ((SDL_SCANCODE_P) (return (quote p))) ((SDL_SCANCODE_Q) (return (quote q)))
   ((SDL_SCANCODE_R) (return (quote r))) ((SDL_SCANCODE_S) (return (quote s)))
   ((SDL_SCANCODE_T) (return (quote t))) ((SDL_SCANCODE_U) (return (quote u)))
   ((SDL_SCANCODE_V) (return (quote v))) ((SDL_SCANCODE_W) (return (quote w)))
   ((SDL_SCANCODE_X) (return (quote x))) ((SDL_SCANCODE_Y) (return (quote y)))
   ((SDL_SCANCODE_Z) (return (quote z)))
   ((SDL_SCANCODE_1) (return (quote |1|)))
   ((SDL_SCANCODE_2) (return (quote |2|)))
   ((SDL_SCANCODE_3) (return (quote |3|)))
   ((SDL_SCANCODE_4) (return (quote |4|)))
   ((SDL_SCANCODE_5) (return (quote |5|)))
   ((SDL_SCANCODE_6) (return (quote |6|)))
   ((SDL_SCANCODE_7) (return (quote |7|)))
   ((SDL_SCANCODE_8) (return (quote |8|)))
   ((SDL_SCANCODE_9) (return (quote |9|)))
   ((SDL_SCANCODE_0) (return (quote |0|)))
   ((SDL_SCANCODE_RETURN) (return (quote return)))
   ((SDL_SCANCODE_ESCAPE) (return (quote escape)))
   ((SDL_SCANCODE_BACKSPACE) (return (quote backspace)))
   ((SDL_SCANCODE_TAB) (return (quote tab)))
   ((SDL_SCANCODE_SPACE) (return (quote space)))
   ((SDL_SCANCODE_MINUS) (return (quote minus)))
   ((SDL_SCANCODE_EQUALS) (return (quote equals)))
   ((SDL_SCANCODE_LEFTBRACKET) (return (quote leftbracket)))
   ((SDL_SCANCODE_RIGHTBRACKET) (return (quote rightbracket)))
   ((SDL_SCANCODE_BACKSLASH) (return (quote backslash)))
   ((SDL_SCANCODE_NONUSHASH) (return (quote nonushash)))
   ((SDL_SCANCODE_SEMICOLON) (return (quote semicolon)))
   ((SDL_SCANCODE_APOSTROPHE) (return (quote apostrophe)))
   ((SDL_SCANCODE_GRAVE) (return (quote grave)))
   ((SDL_SCANCODE_COMMA) (return (quote comma)))
   ((SDL_SCANCODE_PERIOD) (return (quote period)))
   ((SDL_SCANCODE_SLASH) (return (quote slash)))
   ((SDL_SCANCODE_CAPSLOCK) (return (quote capslock)))
   ((SDL_SCANCODE_F1) (return (quote f1)))
   ((SDL_SCANCODE_F2) (return (quote f2)))
   ((SDL_SCANCODE_F3) (return (quote f3)))
   ((SDL_SCANCODE_F4) (return (quote f4)))
   ((SDL_SCANCODE_F5) (return (quote f5)))
   ((SDL_SCANCODE_F6) (return (quote f6)))
   ((SDL_SCANCODE_F7) (return (quote f7)))
   ((SDL_SCANCODE_F8) (return (quote f8)))
   ((SDL_SCANCODE_F9) (return (quote f9)))
   ((SDL_SCANCODE_F10) (return (quote f10)))
   ((SDL_SCANCODE_F11) (return (quote f11)))
   ((SDL_SCANCODE_F12) (return (quote f12)))
   ((SDL_SCANCODE_PRINTSCREEN) (return (quote printscreen)))
   ((SDL_SCANCODE_SCROLLLOCK) (return (quote scrolllock)))
   ((SDL_SCANCODE_PAUSE) (return (quote pause)))
   ((SDL_SCANCODE_INSERT) (return (quote insert)))
   ((SDL_SCANCODE_HOME) (return (quote home)))
   ((SDL_SCANCODE_PAGEUP) (return (quote pageup)))
   ((SDL_SCANCODE_DELETE) (return (quote delete)))
   ((SDL_SCANCODE_END) (return (quote end)))
   ((SDL_SCANCODE_PAGEDOWN) (return (quote pagedown)))
   ((SDL_SCANCODE_RIGHT) (return (quote right)))
   ((SDL_SCANCODE_LEFT) (return (quote left)))
   ((SDL_SCANCODE_DOWN) (return (quote down)))
   ((SDL_SCANCODE_UP) (return (quote up)))
   ((SDL_SCANCODE_NUMLOCKCLEAR) (return (quote numlockclear)))
   ((SDL_SCANCODE_KP_DIVIDE) (return (quote kp-divide)))
   ((SDL_SCANCODE_KP_MULTIPLY) (return (quote kp-multiply)))
   ((SDL_SCANCODE_KP_MINUS) (return (quote kp-minus)))
   ((SDL_SCANCODE_KP_PLUS) (return (quote kp-plus)))
   ((SDL_SCANCODE_KP_ENTER) (return (quote kp-enter)))
   ((SDL_SCANCODE_KP_1) (return (quote kp-1)))
   ((SDL_SCANCODE_KP_2) (return (quote kp-2)))
   ((SDL_SCANCODE_KP_3) (return (quote kp-3)))
   ((SDL_SCANCODE_KP_4) (return (quote kp-4)))
   ((SDL_SCANCODE_KP_5) (return (quote kp-5)))
   ((SDL_SCANCODE_KP_6) (return (quote kp-6)))
   ((SDL_SCANCODE_KP_7) (return (quote kp-7)))
   ((SDL_SCANCODE_KP_8) (return (quote kp-8)))
   ((SDL_SCANCODE_KP_9) (return (quote kp-9)))
   ((SDL_SCANCODE_KP_0) (return (quote kp-0)))
   ((SDL_SCANCODE_KP_PERIOD) (return (quote kp-period)))
   ((SDL_SCANCODE_NONUSBACKSLASH) (return (quote nonusbackslash)))
   ((SDL_SCANCODE_APPLICATION) (return (quote application)))
   ((SDL_SCANCODE_POWER) (return (quote power)))
   ((SDL_SCANCODE_KP_EQUALS) (return (quote kp-equals)))
   ((SDL_SCANCODE_F13) (return (quote f13)))
   ((SDL_SCANCODE_F14) (return (quote f14)))
   ((SDL_SCANCODE_F15) (return (quote f15)))
   ((SDL_SCANCODE_F16) (return (quote f16)))
   ((SDL_SCANCODE_F17) (return (quote f17)))
   ((SDL_SCANCODE_F18) (return (quote f18)))
   ((SDL_SCANCODE_F19) (return (quote f19)))
   ((SDL_SCANCODE_F20) (return (quote f20)))
   ((SDL_SCANCODE_F21) (return (quote f21)))
   ((SDL_SCANCODE_F22) (return (quote f22)))
   ((SDL_SCANCODE_F23) (return (quote f23)))
   ((SDL_SCANCODE_F24) (return (quote f24)))
   ((SDL_SCANCODE_EXECUTE) (return (quote execute)))
   ((SDL_SCANCODE_HELP) (return (quote help)))
   ((SDL_SCANCODE_MENU) (return (quote menu)))
   ((SDL_SCANCODE_SELECT) (return (quote select)))
   ((SDL_SCANCODE_STOP) (return (quote stop)))
   ((SDL_SCANCODE_AGAIN) (return (quote again)))
   ((SDL_SCANCODE_UNDO) (return (quote undo)))
   ((SDL_SCANCODE_CUT) (return (quote cut)))
   ((SDL_SCANCODE_COPY) (return (quote copy)))
   ((SDL_SCANCODE_PASTE) (return (quote paste)))
   ((SDL_SCANCODE_FIND) (return (quote find)))
   ((SDL_SCANCODE_MUTE) (return (quote mute)))
   ((SDL_SCANCODE_VOLUMEUP) (return (quote volumeup)))
   ((SDL_SCANCODE_VOLUMEDOWN) (return (quote volumedown)))
   ((SDL_SCANCODE_KP_COMMA) (return (quote kp-comma)))
   ((SDL_SCANCODE_KP_EQUALSAS400) (return (quote kp-equalsas400)))
   ((SDL_SCANCODE_INTERNATIONAL1) (return (quote international1)))
   ((SDL_SCANCODE_INTERNATIONAL2) (return (quote international2)))
   ((SDL_SCANCODE_INTERNATIONAL3) (return (quote international3)))
   ((SDL_SCANCODE_INTERNATIONAL4) (return (quote international4)))
   ((SDL_SCANCODE_INTERNATIONAL5) (return (quote international5)))
   ((SDL_SCANCODE_INTERNATIONAL6) (return (quote international6)))
   ((SDL_SCANCODE_INTERNATIONAL7) (return (quote international7)))
   ((SDL_SCANCODE_INTERNATIONAL8) (return (quote international8)))
   ((SDL_SCANCODE_INTERNATIONAL9) (return (quote international9)))
   ((SDL_SCANCODE_LANG1) (return (quote lang1)))
   ((SDL_SCANCODE_LANG2) (return (quote lang2)))
   ((SDL_SCANCODE_LANG3) (return (quote lang3)))
   ((SDL_SCANCODE_LANG4) (return (quote lang4)))
   ((SDL_SCANCODE_LANG5) (return (quote lang5)))
   ((SDL_SCANCODE_LANG6) (return (quote lang6)))
   ((SDL_SCANCODE_LANG7) (return (quote lang7)))
   ((SDL_SCANCODE_LANG8) (return (quote lang8)))
   ((SDL_SCANCODE_LANG9) (return (quote lang9)))
   ((SDL_SCANCODE_ALTERASE) (return (quote alterase)))
   ((SDL_SCANCODE_SYSREQ) (return (quote sysreq)))
   ((SDL_SCANCODE_CANCEL) (return (quote cancel)))
   ((SDL_SCANCODE_CLEAR) (return (quote clear)))
   ((SDL_SCANCODE_PRIOR) (return (quote prior)))
   ((SDL_SCANCODE_RETURN2) (return (quote return2)))
   ((SDL_SCANCODE_SEPARATOR) (return (quote separator)))
   ((SDL_SCANCODE_OUT) (return (quote out)))
   ((SDL_SCANCODE_OPER) (return (quote oper)))
   ((SDL_SCANCODE_CLEARAGAIN) (return (quote clearagain)))
   ((SDL_SCANCODE_CRSEL) (return (quote crsel)))
   ((SDL_SCANCODE_EXSEL) (return (quote exsel)))
   ((SDL_SCANCODE_KP_00) (return (quote kp-00)))
   ((SDL_SCANCODE_KP_000) (return (quote kp-000)))
   ((SDL_SCANCODE_THOUSANDSSEPARATOR) (return (quote thousandsseparator)))
   ((SDL_SCANCODE_DECIMALSEPARATOR) (return (quote decimalseparator)))
   ((SDL_SCANCODE_CURRENCYUNIT) (return (quote currencyunit)))
   ((SDL_SCANCODE_CURRENCYSUBUNIT) (return (quote currencysubunit)))
   ((SDL_SCANCODE_KP_LEFTPAREN) (return (quote kp-leftparen)))
   ((SDL_SCANCODE_KP_RIGHTPAREN) (return (quote kp-rightparen)))
   ((SDL_SCANCODE_KP_LEFTBRACE) (return (quote kp-leftbrace)))
   ((SDL_SCANCODE_KP_RIGHTBRACE) (return (quote kp-rightbrace)))
   ((SDL_SCANCODE_KP_TAB) (return (quote kp-tab)))
   ((SDL_SCANCODE_KP_BACKSPACE) (return (quote kp-backspace)))
   ((SDL_SCANCODE_KP_A) (return (quote kp-a)))
   ((SDL_SCANCODE_KP_B) (return (quote kp-b)))
   ((SDL_SCANCODE_KP_C) (return (quote kp-c)))
   ((SDL_SCANCODE_KP_D) (return (quote kp-d)))
   ((SDL_SCANCODE_KP_E) (return (quote kp-e)))
   ((SDL_SCANCODE_KP_F) (return (quote kp-f)))
   ((SDL_SCANCODE_KP_XOR) (return (quote kp-xor)))
   ((SDL_SCANCODE_KP_POWER) (return (quote kp-power)))
   ((SDL_SCANCODE_KP_PERCENT) (return (quote kp-percent)))
   ((SDL_SCANCODE_KP_LESS) (return (quote kp-less)))
   ((SDL_SCANCODE_KP_GREATER) (return (quote kp-greater)))
   ((SDL_SCANCODE_KP_AMPERSAND) (return (quote kp-ampersand)))
   ((SDL_SCANCODE_KP_DBLAMPERSAND) (return (quote kp-dblampersand)))
   ((SDL_SCANCODE_KP_VERTICALBAR) (return (quote kp-verticalbar)))
   ((SDL_SCANCODE_KP_DBLVERTICALBAR) (return (quote kp-dblverticalbar)))
   ((SDL_SCANCODE_KP_COLON) (return (quote kp-colon)))
   ((SDL_SCANCODE_KP_HASH) (return (quote kp-hash)))
   ((SDL_SCANCODE_KP_SPACE) (return (quote kp-space)))
   ((SDL_SCANCODE_KP_AT) (return (quote kp-at)))
   ((SDL_SCANCODE_KP_EXCLAM) (return (quote kp-exclam)))
   ((SDL_SCANCODE_KP_MEMSTORE) (return (quote kp-memstore)))
   ((SDL_SCANCODE_KP_MEMRECALL) (return (quote kp-memrecall)))
   ((SDL_SCANCODE_KP_MEMCLEAR) (return (quote kp-memclear)))
   ((SDL_SCANCODE_KP_MEMADD) (return (quote kp-memadd)))
   ((SDL_SCANCODE_KP_MEMSUBTRACT) (return (quote kp-memsubtract)))
   ((SDL_SCANCODE_KP_MEMMULTIPLY) (return (quote kp-memmultiply)))
   ((SDL_SCANCODE_KP_MEMDIVIDE) (return (quote kp-memdivide)))
   ((SDL_SCANCODE_KP_PLUSMINUS) (return (quote kp-plusminus)))
   ((SDL_SCANCODE_KP_CLEAR) (return (quote kp-clear)))
   ((SDL_SCANCODE_KP_CLEARENTRY) (return (quote kp-clearentry)))
   ((SDL_SCANCODE_KP_BINARY) (return (quote kp-binary)))
   ((SDL_SCANCODE_KP_OCTAL) (return (quote kp-octal)))
   ((SDL_SCANCODE_KP_DECIMAL) (return (quote kp-decimal)))
   ((SDL_SCANCODE_KP_HEXADECIMAL) (return (quote kp-hexadecimal)))
   ((SDL_SCANCODE_LCTRL) (return (quote lctrl)))
   ((SDL_SCANCODE_LSHIFT) (return (quote lshift)))
   ((SDL_SCANCODE_LALT) (return (quote lalt)))
   ((SDL_SCANCODE_LGUI) (return (quote lgui)))
   ((SDL_SCANCODE_RCTRL) (return (quote rctrl)))
   ((SDL_SCANCODE_RSHIFT) (return (quote rshift)))
   ((SDL_SCANCODE_RALT) (return (quote ralt)))
   ((SDL_SCANCODE_RGUI) (return (quote rgui)))
   ((SDL_SCANCODE_MODE) (return (quote mode)))
   ((SDL_SCANCODE_AUDIONEXT) (return (quote audionext)))
   ((SDL_SCANCODE_AUDIOPREV) (return (quote audioprev)))
   ((SDL_SCANCODE_AUDIOSTOP) (return (quote audiostop)))
   ((SDL_SCANCODE_AUDIOPLAY) (return (quote audioplay)))
   ((SDL_SCANCODE_AUDIOMUTE) (return (quote audiomute)))
   ((SDL_SCANCODE_MEDIASELECT) (return (quote mediaselect)))
   ((SDL_SCANCODE_WWW) (return (quote www)))
   ((SDL_SCANCODE_MAIL) (return (quote mail)))
   ((SDL_SCANCODE_CALCULATOR) (return (quote calculator)))
   ((SDL_SCANCODE_COMPUTER) (return (quote computer)))
   ((SDL_SCANCODE_AC_SEARCH) (return (quote ac-search)))
   ((SDL_SCANCODE_AC_HOME) (return (quote ac-home)))
   ((SDL_SCANCODE_AC_BACK) (return (quote ac-back)))
   ((SDL_SCANCODE_AC_FORWARD) (return (quote ac-forward)))
   ((SDL_SCANCODE_AC_STOP) (return (quote ac-stop)))
   ((SDL_SCANCODE_AC_REFRESH) (return (quote ac-refresh)))
   ((SDL_SCANCODE_AC_BOOKMARKS) (return (quote ac-bookmarks)))
   ((SDL_SCANCODE_BRIGHTNESSDOWN) (return (quote brightnessdown)))
   ((SDL_SCANCODE_BRIGHTNESSUP) (return (quote brightnessup)))
   ((SDL_SCANCODE_DISPLAYSWITCH) (return (quote displayswitch)))
   ((SDL_SCANCODE_KBDILLUMTOGGLE) (return (quote kbdillumtoggle)))
   ((SDL_SCANCODE_KBDILLUMDOWN) (return (quote kbdillumdown)))
   ((SDL_SCANCODE_KBDILLUMUP) (return (quote kbdillumup)))
   ((SDL_SCANCODE_EJECT) (return (quote eject)))
   ((SDL_SCANCODE_SLEEP) (return (quote sleep)))
   ((SDL_SCANCODE_APP1) (return (quote app1)))
   ((SDL_SCANCODE_APP2) (return (quote app2)))
   ((SDL_SCANCODE_AUDIOREWIND) (return (quote audiorewind)))
   ((SDL_SCANCODE_AUDIOFASTFORWARD) (return (quote audiofastforward)))
   (else (return (quote unknown)))))
 (define-cfn
  keycode->symbol
  (v :: SDL_Keycode)
  ::ScmObj
  :static
  (case v ((SDLK_RETURN) (return (quote return)))
   ((SDLK_ESCAPE) (return (quote escape)))
   ((SDLK_BACKSPACE) (return (quote backspace)))
   ((SDLK_TAB) (return (quote tab))) ((SDLK_SPACE) (return (quote space)))
   ((SDLK_EXCLAIM) (return (quote exclaim)))
   ((SDLK_QUOTEDBL) (return (quote quotedbl)))
   ((SDLK_HASH) (return (quote hash)))
   ((SDLK_PERCENT) (return (quote percent)))
   ((SDLK_DOLLAR) (return (quote dollar)))
   ((SDLK_AMPERSAND) (return (quote ampersand)))
   ((SDLK_QUOTE) (return (quote quote)))
   ((SDLK_LEFTPAREN) (return (quote leftparen)))
   ((SDLK_RIGHTPAREN) (return (quote rightparen)))
   ((SDLK_ASTERISK) (return (quote asterisk)))
   ((SDLK_PLUS) (return (quote plus))) ((SDLK_COMMA) (return (quote comma)))
   ((SDLK_MINUS) (return (quote minus)))
   ((SDLK_PERIOD) (return (quote period)))
   ((SDLK_SLASH) (return (quote slash))) ((SDLK_0) (return (quote |0|)))
   ((SDLK_1) (return (quote |1|))) ((SDLK_2) (return (quote |2|)))
   ((SDLK_3) (return (quote |3|))) ((SDLK_4) (return (quote |4|)))
   ((SDLK_5) (return (quote |5|))) ((SDLK_6) (return (quote |6|)))
   ((SDLK_7) (return (quote |7|))) ((SDLK_8) (return (quote |8|)))
   ((SDLK_9) (return (quote |9|))) ((SDLK_COLON) (return (quote colon)))
   ((SDLK_SEMICOLON) (return (quote semicolon)))
   ((SDLK_LESS) (return (quote less))) ((SDLK_EQUALS) (return (quote equals)))
   ((SDLK_GREATER) (return (quote greater)))
   ((SDLK_QUESTION) (return (quote question))) ((SDLK_AT) (return (quote at)))
   ((SDLK_LEFTBRACKET) (return (quote leftbracket)))
   ((SDLK_BACKSLASH) (return (quote backslash)))
   ((SDLK_RIGHTBRACKET) (return (quote rightbracket)))
   ((SDLK_CARET) (return (quote caret)))
   ((SDLK_UNDERSCORE) (return (quote underscore)))
   ((SDLK_BACKQUOTE) (return (quote backquote))) ((SDLK_a) (return (quote a)))
   ((SDLK_b) (return (quote b))) ((SDLK_c) (return (quote c)))
   ((SDLK_d) (return (quote d))) ((SDLK_e) (return (quote e)))
   ((SDLK_f) (return (quote f))) ((SDLK_g) (return (quote g)))
   ((SDLK_h) (return (quote h))) ((SDLK_i) (return (quote i)))
   ((SDLK_j) (return (quote j))) ((SDLK_k) (return (quote k)))
   ((SDLK_l) (return (quote l))) ((SDLK_m) (return (quote m)))
   ((SDLK_n) (return (quote n))) ((SDLK_o) (return (quote o)))
   ((SDLK_p) (return (quote p))) ((SDLK_q) (return (quote q)))
   ((SDLK_r) (return (quote r))) ((SDLK_s) (return (quote s)))
   ((SDLK_t) (return (quote t))) ((SDLK_u) (return (quote u)))
   ((SDLK_v) (return (quote v))) ((SDLK_w) (return (quote w)))
   ((SDLK_x) (return (quote x))) ((SDLK_y) (return (quote y)))
   ((SDLK_z) (return (quote z))) ((SDLK_CAPSLOCK) (return (quote capslock)))
   ((SDLK_F1) (return (quote f1))) ((SDLK_F2) (return (quote f2)))
   ((SDLK_F3) (return (quote f3))) ((SDLK_F4) (return (quote f4)))
   ((SDLK_F5) (return (quote f5))) ((SDLK_F6) (return (quote f6)))
   ((SDLK_F7) (return (quote f7))) ((SDLK_F8) (return (quote f8)))
   ((SDLK_F9) (return (quote f9))) ((SDLK_F10) (return (quote f10)))
   ((SDLK_F11) (return (quote f11))) ((SDLK_F12) (return (quote f12)))
   ((SDLK_PRINTSCREEN) (return (quote printscreen)))
   ((SDLK_SCROLLLOCK) (return (quote scrolllock)))
   ((SDLK_PAUSE) (return (quote pause)))
   ((SDLK_INSERT) (return (quote insert))) ((SDLK_HOME) (return (quote home)))
   ((SDLK_PAGEUP) (return (quote pageup)))
   ((SDLK_DELETE) (return (quote delete))) ((SDLK_END) (return (quote end)))
   ((SDLK_PAGEDOWN) (return (quote pagedown)))
   ((SDLK_RIGHT) (return (quote right))) ((SDLK_LEFT) (return (quote left)))
   ((SDLK_DOWN) (return (quote down))) ((SDLK_UP) (return (quote up)))
   ((SDLK_NUMLOCKCLEAR) (return (quote numlockclear)))
   ((SDLK_KP_DIVIDE) (return (quote kp-divide)))
   ((SDLK_KP_MULTIPLY) (return (quote kp-multiply)))
   ((SDLK_KP_MINUS) (return (quote kp-minus)))
   ((SDLK_KP_PLUS) (return (quote kp-plus)))
   ((SDLK_KP_ENTER) (return (quote kp-enter)))
   ((SDLK_KP_1) (return (quote kp-1))) ((SDLK_KP_2) (return (quote kp-2)))
   ((SDLK_KP_3) (return (quote kp-3))) ((SDLK_KP_4) (return (quote kp-4)))
   ((SDLK_KP_5) (return (quote kp-5))) ((SDLK_KP_6) (return (quote kp-6)))
   ((SDLK_KP_7) (return (quote kp-7))) ((SDLK_KP_8) (return (quote kp-8)))
   ((SDLK_KP_9) (return (quote kp-9))) ((SDLK_KP_0) (return (quote kp-0)))
   ((SDLK_KP_PERIOD) (return (quote kp-period)))
   ((SDLK_APPLICATION) (return (quote application)))
   ((SDLK_POWER) (return (quote power)))
   ((SDLK_KP_EQUALS) (return (quote kp-equals)))
   ((SDLK_F13) (return (quote f13))) ((SDLK_F14) (return (quote f14)))
   ((SDLK_F15) (return (quote f15))) ((SDLK_F16) (return (quote f16)))
   ((SDLK_F17) (return (quote f17))) ((SDLK_F18) (return (quote f18)))
   ((SDLK_F19) (return (quote f19))) ((SDLK_F20) (return (quote f20)))
   ((SDLK_F21) (return (quote f21))) ((SDLK_F22) (return (quote f22)))
   ((SDLK_F23) (return (quote f23))) ((SDLK_F24) (return (quote f24)))
   ((SDLK_EXECUTE) (return (quote execute)))
   ((SDLK_HELP) (return (quote help))) ((SDLK_MENU) (return (quote menu)))
   ((SDLK_SELECT) (return (quote select))) ((SDLK_STOP) (return (quote stop)))
   ((SDLK_AGAIN) (return (quote again))) ((SDLK_UNDO) (return (quote undo)))
   ((SDLK_CUT) (return (quote cut))) ((SDLK_COPY) (return (quote copy)))
   ((SDLK_PASTE) (return (quote paste))) ((SDLK_FIND) (return (quote find)))
   ((SDLK_MUTE) (return (quote mute)))
   ((SDLK_VOLUMEUP) (return (quote volumeup)))
   ((SDLK_VOLUMEDOWN) (return (quote volumedown)))
   ((SDLK_KP_COMMA) (return (quote kp-comma)))
   ((SDLK_KP_EQUALSAS400) (return (quote kp-equalsas400)))
   ((SDLK_ALTERASE) (return (quote alterase)))
   ((SDLK_SYSREQ) (return (quote sysreq)))
   ((SDLK_CANCEL) (return (quote cancel)))
   ((SDLK_CLEAR) (return (quote clear))) ((SDLK_PRIOR) (return (quote prior)))
   ((SDLK_RETURN2) (return (quote return2)))
   ((SDLK_SEPARATOR) (return (quote separator)))
   ((SDLK_OUT) (return (quote out))) ((SDLK_OPER) (return (quote oper)))
   ((SDLK_CLEARAGAIN) (return (quote clearagain)))
   ((SDLK_CRSEL) (return (quote crsel))) ((SDLK_EXSEL) (return (quote exsel)))
   ((SDLK_KP_00) (return (quote kp-00)))
   ((SDLK_KP_000) (return (quote kp-000)))
   ((SDLK_THOUSANDSSEPARATOR) (return (quote thousandsseparator)))
   ((SDLK_DECIMALSEPARATOR) (return (quote decimalseparator)))
   ((SDLK_CURRENCYUNIT) (return (quote currencyunit)))
   ((SDLK_CURRENCYSUBUNIT) (return (quote currencysubunit)))
   ((SDLK_KP_LEFTPAREN) (return (quote kp-leftparen)))
   ((SDLK_KP_RIGHTPAREN) (return (quote kp-rightparen)))
   ((SDLK_KP_LEFTBRACE) (return (quote kp-leftbrace)))
   ((SDLK_KP_RIGHTBRACE) (return (quote kp-rightbrace)))
   ((SDLK_KP_TAB) (return (quote kp-tab)))
   ((SDLK_KP_BACKSPACE) (return (quote kp-backspace)))
   ((SDLK_KP_A) (return (quote kp-a))) ((SDLK_KP_B) (return (quote kp-b)))
   ((SDLK_KP_C) (return (quote kp-c))) ((SDLK_KP_D) (return (quote kp-d)))
   ((SDLK_KP_E) (return (quote kp-e))) ((SDLK_KP_F) (return (quote kp-f)))
   ((SDLK_KP_XOR) (return (quote kp-xor)))
   ((SDLK_KP_POWER) (return (quote kp-power)))
   ((SDLK_KP_PERCENT) (return (quote kp-percent)))
   ((SDLK_KP_LESS) (return (quote kp-less)))
   ((SDLK_KP_GREATER) (return (quote kp-greater)))
   ((SDLK_KP_AMPERSAND) (return (quote kp-ampersand)))
   ((SDLK_KP_DBLAMPERSAND) (return (quote kp-dblampersand)))
   ((SDLK_KP_VERTICALBAR) (return (quote kp-verticalbar)))
   ((SDLK_KP_DBLVERTICALBAR) (return (quote kp-dblverticalbar)))
   ((SDLK_KP_COLON) (return (quote kp-colon)))
   ((SDLK_KP_HASH) (return (quote kp-hash)))
   ((SDLK_KP_SPACE) (return (quote kp-space)))
   ((SDLK_KP_AT) (return (quote kp-at)))
   ((SDLK_KP_EXCLAM) (return (quote kp-exclam)))
   ((SDLK_KP_MEMSTORE) (return (quote kp-memstore)))
   ((SDLK_KP_MEMRECALL) (return (quote kp-memrecall)))
   ((SDLK_KP_MEMCLEAR) (return (quote kp-memclear)))
   ((SDLK_KP_MEMADD) (return (quote kp-memadd)))
   ((SDLK_KP_MEMSUBTRACT) (return (quote kp-memsubtract)))
   ((SDLK_KP_MEMMULTIPLY) (return (quote kp-memmultiply)))
   ((SDLK_KP_MEMDIVIDE) (return (quote kp-memdivide)))
   ((SDLK_KP_PLUSMINUS) (return (quote kp-plusminus)))
   ((SDLK_KP_CLEAR) (return (quote kp-clear)))
   ((SDLK_KP_CLEARENTRY) (return (quote kp-clearentry)))
   ((SDLK_KP_BINARY) (return (quote kp-binary)))
   ((SDLK_KP_OCTAL) (return (quote kp-octal)))
   ((SDLK_KP_DECIMAL) (return (quote kp-decimal)))
   ((SDLK_KP_HEXADECIMAL) (return (quote kp-hexadecimal)))
   ((SDLK_LCTRL) (return (quote lctrl)))
   ((SDLK_LSHIFT) (return (quote lshift))) ((SDLK_LALT) (return (quote lalt)))
   ((SDLK_LGUI) (return (quote lgui))) ((SDLK_RCTRL) (return (quote rctrl)))
   ((SDLK_RSHIFT) (return (quote rshift))) ((SDLK_RALT) (return (quote ralt)))
   ((SDLK_RGUI) (return (quote rgui))) ((SDLK_MODE) (return (quote mode)))
   ((SDLK_AUDIONEXT) (return (quote audionext)))
   ((SDLK_AUDIOPREV) (return (quote audioprev)))
   ((SDLK_AUDIOSTOP) (return (quote audiostop)))
   ((SDLK_AUDIOPLAY) (return (quote audioplay)))
   ((SDLK_AUDIOMUTE) (return (quote audiomute)))
   ((SDLK_MEDIASELECT) (return (quote mediaselect)))
   ((SDLK_WWW) (return (quote www))) ((SDLK_MAIL) (return (quote mail)))
   ((SDLK_CALCULATOR) (return (quote calculator)))
   ((SDLK_COMPUTER) (return (quote computer)))
   ((SDLK_AC_SEARCH) (return (quote ac-search)))
   ((SDLK_AC_HOME) (return (quote ac-home)))
   ((SDLK_AC_BACK) (return (quote ac-back)))
   ((SDLK_AC_FORWARD) (return (quote ac-forward)))
   ((SDLK_AC_STOP) (return (quote ac-stop)))
   ((SDLK_AC_REFRESH) (return (quote ac-refresh)))
   ((SDLK_AC_BOOKMARKS) (return (quote ac-bookmarks)))
   ((SDLK_BRIGHTNESSDOWN) (return (quote brightnessdown)))
   ((SDLK_BRIGHTNESSUP) (return (quote brightnessup)))
   ((SDLK_DISPLAYSWITCH) (return (quote displayswitch)))
   ((SDLK_KBDILLUMTOGGLE) (return (quote kbdillumtoggle)))
   ((SDLK_KBDILLUMDOWN) (return (quote kbdillumdown)))
   ((SDLK_KBDILLUMUP) (return (quote kbdillumup)))
   ((SDLK_EJECT) (return (quote eject))) ((SDLK_SLEEP) (return (quote sleep)))
   ((SDLK_APP1) (return (quote app1))) ((SDLK_APP2) (return (quote app2)))
   ((SDLK_AUDIOREWIND) (return (quote audiorewind)))
   ((SDLK_AUDIOFASTFORWARD) (return (quote audiofastforward)))
   (else (return (quote unknown)))))
 (define-cfn
  kmod->symbols
  (v :: Uint16)
  ::ScmObj
  :static
  (let* ((syms SCM_NIL))
   (when (logand v KMOD_LSHIFT) (set! syms (Scm_Cons (quote lshift) syms)))
   (when (logand v KMOD_RSHIFT) (set! syms (Scm_Cons (quote rshift) syms)))
   (when (logand v KMOD_LCTRL) (set! syms (Scm_Cons (quote lctrl) syms)))
   (when (logand v KMOD_RCTRL) (set! syms (Scm_Cons (quote rctrl) syms)))
   (when (logand v KMOD_LALT) (set! syms (Scm_Cons (quote lalt) syms)))
   (when (logand v KMOD_RALT) (set! syms (Scm_Cons (quote ralt) syms)))
   (when (logand v KMOD_LGUI) (set! syms (Scm_Cons (quote lgui) syms)))
   (when (logand v KMOD_RGUI) (set! syms (Scm_Cons (quote rgui) syms)))
   (when (logand v KMOD_NUM) (set! syms (Scm_Cons (quote num) syms)))
   (when (logand v KMOD_CAPS) (set! syms (Scm_Cons (quote caps) syms)))
   (when (logand v KMOD_MODE) (set! syms (Scm_Cons (quote mode) syms)))
   (when (logand v KMOD_CTRL) (set! syms (Scm_Cons (quote ctrl) syms)))
   (when (logand v KMOD_SHIFT) (set! syms (Scm_Cons (quote shift) syms)))
   (when (logand v KMOD_ALT) (set! syms (Scm_Cons (quote alt) syms)))
   (when (logand v KMOD_GUI) (set! syms (Scm_Cons (quote gui) syms)))
   (return syms)))
 (define-cfn
  window-event->symbol
  (v :: SDL_WindowEventID)
  ::ScmObj
  :static
  (case v ((SDL_WINDOWEVENT_SHOWN) (return (quote window-shown)))
   ((SDL_WINDOWEVENT_HIDDEN) (return (quote window-hidden)))
   ((SDL_WINDOWEVENT_EXPOSED) (return (quote window-exposed)))
   ((SDL_WINDOWEVENT_MOVED) (return (quote window-moved)))
   ((SDL_WINDOWEVENT_RESIZED) (return (quote window-resized)))
   ((SDL_WINDOWEVENT_SIZE_CHANGED) (return (quote window-size-changed)))
   ((SDL_WINDOWEVENT_MINIMIZED) (return (quote window-minimized)))
   ((SDL_WINDOWEVENT_MAXIMIZED) (return (quote window-maximized)))
   ((SDL_WINDOWEVENT_RESTORED) (return (quote window-restored)))
   ((SDL_WINDOWEVENT_ENTER) (return (quote window-enter)))
   ((SDL_WINDOWEVENT_LEAVE) (return (quote window-leave)))
   ((SDL_WINDOWEVENT_FOCUS_GAINED) (return (quote window-focus-gained)))
   ((SDL_WINDOWEVENT_FOCUS_LOST) (return (quote window-focus-lost)))
   ((SDL_WINDOWEVENT_CLOSE) (return (quote window-close)))
   ((SDL_WINDOWEVENT_TAKE_FOCUS) (return (quote window-take-focus)))
   ((SDL_WINDOWEVENT_HIT_TEST) (return (quote window-hit-test)))
   (else (return (quote window-unknown-event)))))
 (define-cfn
  axis->symbol
  (v :: SDL_GameControllerAxis)
  ::ScmObj
  :static
  (case v ((SDL_CONTROLLER_AXIS_LEFTX) (return (quote leftx)))
   ((SDL_CONTROLLER_AXIS_LEFTY) (return (quote lefty)))
   ((SDL_CONTROLLER_AXIS_RIGHTX) (return (quote rightx)))
   ((SDL_CONTROLLER_AXIS_RIGHTY) (return (quote righty)))
   ((SDL_CONTROLLER_AXIS_TRIGGERLEFT) (return (quote triggerleft)))
   ((SDL_CONTROLLER_AXIS_TRIGGERRIGHT) (return (quote triggerright)))
   (else (return (quote unknown)))))
 (define-cfn
  button->symbol
  (v :: SDL_GameControllerButton)
  ::ScmObj
  :static
  (case v ((SDL_CONTROLLER_BUTTON_A) (return (quote a)))
   ((SDL_CONTROLLER_BUTTON_B) (return (quote b)))
   ((SDL_CONTROLLER_BUTTON_X) (return (quote x)))
   ((SDL_CONTROLLER_BUTTON_Y) (return (quote y)))
   ((SDL_CONTROLLER_BUTTON_BACK) (return (quote back)))
   ((SDL_CONTROLLER_BUTTON_GUIDE) (return (quote guide)))
   ((SDL_CONTROLLER_BUTTON_START) (return (quote start)))
   ((SDL_CONTROLLER_BUTTON_LEFTSTICK) (return (quote leftstick)))
   ((SDL_CONTROLLER_BUTTON_RIGHTSTICK) (return (quote rightstick)))
   ((SDL_CONTROLLER_BUTTON_LEFTSHOULDER) (return (quote leftshoulder)))
   ((SDL_CONTROLLER_BUTTON_RIGHTSHOULDER) (return (quote rightshoulder)))
   ((SDL_CONTROLLER_BUTTON_DPAD_UP) (return (quote dpad-up)))
   ((SDL_CONTROLLER_BUTTON_DPAD_DOWN) (return (quote dpad-down)))
   ((SDL_CONTROLLER_BUTTON_DPAD_LEFT) (return (quote dpad-left)))
   ((SDL_CONTROLLER_BUTTON_DPAD_RIGHT) (return (quote dpad-right)))
   (else (return (quote unknown)))))
 (define-cfn
  mouse-button-state->symbols
  (v :: Uint32)
  ::ScmObj
  :static
  (let* ((syms SCM_NIL))
   (when (logand v SDL_BUTTON_LMASK) (set! syms (Scm_Cons (quote left) syms)))
   (when (logand v SDL_BUTTON_MMASK) (set! syms (Scm_Cons (quote middle) syms)))
   (when (logand v SDL_BUTTON_RMASK) (set! syms (Scm_Cons (quote right) syms)))
   (when (logand v SDL_BUTTON_X1MASK) (set! syms (Scm_Cons (quote x1) syms)))
   (when (logand v SDL_BUTTON_X2MASK) (set! syms (Scm_Cons (quote x2) syms)))
   (return syms)))
 (define-cfn
  mouse-button->symbol
  (v :: Uint8)
  ::ScmObj
  :static
  (case v ((SDL_BUTTON_LEFT) (return (quote left)))
   ((SDL_BUTTON_MIDDLE) (return (quote middle)))
   ((SDL_BUTTON_RIGHT) (return (quote right)))
   ((SDL_BUTTON_X1) (return (quote x1))) ((SDL_BUTTON_X2) (return (quote x2)))
   (else (return (quote unknown)))))
 (define-cfn
  hat-position->symbol
  (v :: Uint8)
  ::ScmObj
  :static
  (case v ((SDL_HAT_CENTERED) (return (quote centered)))
   ((SDL_HAT_UP) (return (quote up))) ((SDL_HAT_RIGHT) (return (quote right)))
   ((SDL_HAT_DOWN) (return (quote down)))
   ((SDL_HAT_LEFT) (return (quote left)))
   ((SDL_HAT_RIGHTUP) (return (quote rightup)))
   ((SDL_HAT_RIGHTDOWN) (return (quote rightdown)))
   ((SDL_HAT_LEFTUP) (return (quote leftup)))
   ((SDL_HAT_LEFTDOWN) (return (quote leftdown)))
   (else (return (quote unknown))))))
